#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -r 0
rm *.OpenFOAM
rm system/controlDict
cleanCase
foamClearPolyMesh
