#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Initial files
cp -r org0 0
cp system/controlDict0 system/controlDict
cp system/fvSolution0 system/fvSolution
blockMesh
setFields

time_extend(){
foamDictionary system/controlDict -entry endTime -set $1
foamDictionary system/controlDict -entry writeInterval -set $2
foamDictionary system/controlDict -entry maxDeltaT -set $3
}

new_deltaT(){
local LATEST_TIME=$(foamListTimes -withZero -latestTime | tail -n 1)
foamDictionary $LATEST_TIME/uniform/time -entry deltaT -set 1e-10
}

copy_bcU(){
    local buff=$(foamDictionary $1 -entry boundaryField.walls -value)
    foamDictionary $1 -entry boundaryField.outlet -set "$buff"
}
copy_bcP(){
    local buff=$(foamDictionary $1 -entry boundaryField.walls -value)
    local buffv=$(foamDictionary $1 -entry boundaryField.outlet.value -value)
    foamDictionary $1 -entry boundaryField.outlet -set "$buff"
    foamDictionary $1 -entry boundaryField.outlet.value -set "$buffv"
}
copy_bcT(){
    local buff=$(foamDictionary $1 -entry boundaryField.walls -value)
    foamDictionary $1 -entry boundaryField.outlet -set "$buff"
    foamDictionary $1 -entry boundaryField.outlet.value -remove
    foamDictionary $1 -entry boundaryField.outlet.valueFraction -remove
}
close_outlet()
(
    local LATEST_TIME=$(foamListTimes -withZero -latestTime | tail -n 1)
    copy_bcP $LATEST_TIME/p_rgh
    copy_bcT $LATEST_TIME/T
    copy_bcU $LATEST_TIME/U
)

# Echoes all commands before executing.
set -o xtrace

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`
# cpus
cpus=`getNumberOfProcessors`

# fill
phase='_fill'
runApplication decomposePar
mv log.decomposePar 'log.decomposePar'$phase
mpirun -np $cpus -hostfile machines $application -parallel > 'log.'$application 2>&1
mv 'log.'$application 'log.'$application$phase
runApplication reconstructPar
mv log.reconstructPar 'log.reconstructPar'$phase

# pack1
phase='_pack1'
time_extend 0.475 0.1 1e-4
new_deltaT
close_outlet
rm -r processor*
runApplication decomposePar
mv log.decomposePar 'log.decomposePar'$phase
mpirun -np $cpus -hostfile machines $application -parallel > 'log.'$application 2>&1
mv 'log.'$application 'log.'$application$phase
runApplication reconstructPar
mv log.reconstructPar 'log.reconstructPar'$phase

# pack2
phase='_pack2'
time_extend 6 0.5 1e-3
rm -r processor*
runApplication decomposePar
mv log.decomposePar 'log.decomposePar'$phase
mpirun -np $cpus -hostfile machines $application -parallel > 'log.'$application 2>&1
mv 'log.'$application 'log.'$application$phase
runApplication reconstructPar
mv log.reconstructPar 'log.reconstructPar'$phase
