#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Initial files
cp -r org0 0
cp system/controlDict0 system/controlDict
cp system/fvSolution0 system/fvSolution
blockMesh
setFields

time_extend(){
foamDictionary system/controlDict -entry endTime -set $1
foamDictionary system/controlDict -entry writeInterval -set $2
foamDictionary system/controlDict -entry maxDeltaT -set $3
}

new_deltaT(){
local LATEST_TIME=$(foamListTimes -withZero -latestTime | tail -n 1)
sed -i -e 's/^deltaT\s.*;/deltaT 1e-10;/g' $LATEST_TIME/uniform/time # change init deltaT
}

close_outlet()
{
    local LATEST_TIME=$(foamListTimes -withZero -latestTime | tail -n 1)

    # pressure
    foamDictionary ${LATEST_TIME}/p_rgh -entry boundaryField.outlet \
        -set "{type fixedFluxPressure; value uniform 1e5;}" || exit 1
    # velocity
    foamDictionary ${LATEST_TIME}/U -entry boundaryField.outlet \
        -set "{type fixedValue; value uniform (0 0 0);}" || exit 1
    # temperature
    foamDictionary ${LATEST_TIME}/T -entry boundaryField.outlet \
        -set "{type fixedValue; value uniform 323.15;}" || exit 1
}

# Echoes all commands before executing.
set -o xtrace

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# fill
phase='_fill'
runApplication $application
mv 'log.'$application 'log.'$application$phase

# pack1
phase='_pack1'
time_extend 0.475 0.1 1e-4
new_detaT
close_outlet
runApplication $application
mv 'log.'$application 'log.'$application$phase

# pack2
phase='_pack2'
time_extend 6 0.5 1e-3
runApplication $application
mv 'log.'$application 'log.'$application$phase
