#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Initial files
cp -r org0 0
cp system/controlDict0 system/controlDict
cp system/fvSolution0 system/fvSolution
blockMesh
setFields

# Echoes all commands before executing.
set -o xtrace

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# fill
phase='_fill'
runApplication $application
mv 'log.'$application 'log.'$application$phase

# pack1
phase='_pack1'
sed -i -e 's/^deltaT\s.*;/deltaT 1e-10;/g' 0.135/uniform/time # change init deltaT
changeDictionary -latestTime -dict system/changeDictionaryDict.bcpack
changeDictionary -instance system -dict system/changeDictionaryDict.ctrl1
runApplication $application
mv 'log.'$application 'log.'$application$phase

# pack2
phase='_pack2'
changeDictionary -instance system -dict system/changeDictionaryDict.ctrl2
runApplication $application
mv 'log.'$application 'log.'$application$phase
