#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
foamClearPolyMesh

rm *.png
rm system/controlDict
rm constant/solidificationProperties
rm -r 0
# ----------------------------------------------------------------- end-of-file
