#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Initial files
cp -r org0 0
cp system/controlDict0 system/controlDict
cp constant/solidificationProperties0 constant/solidificationProperties
blockMesh

# Echoes all commands before executing.
set -o xtrace

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# fill
phase='_1'
runApplication $application
mv 'log.'$application 'log.'$application$phase

# pack1
phase='_2'
changeDictionary -instance system -dict system/changeDictionaryDict.ctrl
changeDictionary -instance constant -dict system/changeDictionaryDict.cons
sed -i -e 's/^deltaT\s.*;/deltaT 1e-8;/g' 0.005/uniform/time # change init deltaT
runApplication $application
mv 'log.'$application 'log.'$application$phase
