#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
foamClearPolyMesh

rm 0/T.poly
rm 0/T.air
rm *.png
# ----------------------------------------------------------------- end-of-file
