#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Echoes all commands before executing.
set -o xtrace

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`


blockMesh

runApplication $application
