#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

blockMesh

cp -r org0 0
runApplication $application
foamCalc addSubtract T add -value -273.15 -resultName Tc

probeLocations
