#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

#--- SIMULATION PARAMETERS 

fill_rate=20e-6 # 1e-6 = 1 ccm/s
p_pack=27e6

TimeEndFILL=0.45
dtWriteFILL=0.01

TimeEndPACK=0.55
dtWritePACK=0.01

TimeEndHOLD=15.05
dtWriteHOLD=0.5

# Initial files
rm log.de* log.re* log.op*
rm -rf processor* postProcessing/residuals
cp system/controlDict0 system/controlDict
cp system/fvSolution0 system/fvSolution


# Echoes all commands before executing.
set -o xtrace

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# run funcs
ctrl_time_set(){
foamDictionary system/controlDict -entry endTime -set $1
foamDictionary system/controlDict -entry writeInterval -set $2
foamDictionary system/controlDict -entry maxDeltaT -set $3
}

new_deltaT(){
local LATEST_TIME=$(foamListTimes -withZero -latestTime | tail -n 1)
foamDictionary $LATEST_TIME/uniform/time -entry deltaT -set 1e-10
}


change_bcU(){
    foamDictionary $1 -entry boundaryField.outlet.value -set "uniform (0 0 0)"
    foamDictionary $1 -entry boundaryField.outlet.type -set "fixedValue"
    foamDictionary $1 -entry boundaryField.inlet.type -set "zeroGradient"
}
change_bcP(){
    foamDictionary $1 -entry boundaryField.outlet.type -set "zeroGradient"
    foamDictionary $1 -entry boundaryField.inlet.type -set "uniformFixedValue"
    foamDictionary $1 -entry boundaryField.inlet -add "uniformValue"
    foamDictionary $1 -entry boundaryField.inlet.uniformValue -set "table ((0 $p_pack)(1000.0 $p_pack))"
}
change_bcT(){
    local buff=$(foamDictionary $1 -entry boundaryField.walls.h -value)
    foamDictionary $1 -entry boundaryField.outlet.h -set "$buff"
}

change_bc()
(
    local LATEST_TIME=$(foamListTimes -withZero -latestTime | tail -n 1)
    change_bcP $LATEST_TIME/p_rgh
    change_bcT $LATEST_TIME/T
    change_bcU $LATEST_TIME/U
)

# cluster_run()
# {
# # cpus
#     cpus=`getNumberOfProcessors`
#     mpirun -np $cpus -hostfile machines $application -parallel > 'log.'$application 2>&1
# }


# Get application name
application=`getApplication`

# fill
phase='_fill'
ctrl_time_set $TimeEndFILL $dtWriteFILL 0.01
foamDictionary 0/U -entry boundaryField.inlet.volumetricFlowRate -set $fill_rate
runApplication decomposePar || exit 1 # prepare parallel
runParallel $application -fillEnd 0.98 || exit 1
mv 'log.'$application 'log.'$application$phase # archive log

# pack1
phase='_pack'
ctrl_time_set $TimeEndPACK $dtWritePACK 0.01
foamDictionary system/controlDict -entry maxSolidCo -set 3e-4
reconstructPar || exit 1
new_deltaT
change_bc
rm -r processor*
decomposePar || exit 1
runParallel $application || exit 1
mv 'log.'$application 'log.'$application$phase

# pack2
phase='_hold'
ctrl_time_set $TimeEndHOLD $dtWriteHOLD 5e-4
runParallel $application || exit 1
mv 'log.'$application 'log.'$application$phase
reconstructPar || exit 1

# Cleaning
rm -r processor*
