#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wclean
wclean libso mojLibForces
wclean openInjMoldSimF

# ----------------------------------------------------------------- end-of-file
