#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmake
wmake openInjMoldSimF
wmake libso mojLibForces 

# ----------------------------------------------------------------- end-of-file
